package com.example.meepmeep;

import com.acmerobotics.roadrunner.geometry.Pose2d;
import com.acmerobotics.roadrunner.geometry.Vector2d;
import com.noahbres.meepmeep.MeepMeep;
import com.noahbres.meepmeep.core.colorscheme.scheme.ColorSchemeBlueLight;
import com.noahbres.meepmeep.core.colorscheme.scheme.ColorSchemeRedLight;
import com.noahbres.meepmeep.roadrunner.DefaultBotBuilder;
import com.noahbres.meepmeep.roadrunner.entity.RoadRunnerBotEntity;

import java.util.Vector;

public class MeepMeepTesting {
    public static void main(String[] args) {
        MeepMeep meepMeep = new MeepMeep(800);

        RoadRunnerBotEntity newCycle = new DefaultBotBuilder(meepMeep)
                // Set bot constraints: maxVel, maxAccel, maxAngVel, maxAngAccel, track width
                .setColorScheme(new ColorSchemeBlueLight())
                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
                .setDimensions(13.5, 17)
                .followTrajectorySequence(drive ->
                        drive.trajectorySequenceBuilder(new Pose2d(-30, 61.5, Math.toRadians(270)))

                                .splineTo(new Vector2d(22.3, 52.511), Math.toRadians(-45))
                                .build()

                );

        meepMeep.setBackground(MeepMeep.Background.FIELD_POWERPLAY_OFFICIAL)
                .setDarkMode(true)
                .setBackgroundAlpha(0.95f)
                //.addEntity(GBBlueLeft1)
                .addEntity(newCycle)
                .start();
    }
}
// RoadRunnerBotEntity BlueLeftCycle2 = new DefaultBotBuilder(meepMeep)
//                // Set bot constraints: maxVel, maxAccel, maxAngVel, maxAngAccel, track width
//                .setColorScheme(new ColorSchemeBlueLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(35, 61.5, Math.toRadians(270)))
//                                .splineToConstantHeading(new Vector2d(24,12), Math.toRadians(180))
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .splineToConstantHeading(new Vector2d(50,12), Math.toRadians(0))
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(12)
//                                .waitSeconds(1)
//                                .strafeLeft(10)
//                                .build()
//                );
//        RoadRunnerBotEntity BlueLeftCycle1 = new DefaultBotBuilder(meepMeep)
//                // Set bot constraints: maxVel, maxAccel, maxAngVel, maxAngAccel, track width
//                .setColorScheme(new ColorSchemeBlueLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(35, 61.5, Math.toRadians(270)))
//                                .splineToConstantHeading(new Vector2d(24,12), Math.toRadians(180))
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .splineToConstantHeading(new Vector2d(50,12), Math.toRadians(0))
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(12)
//                                .waitSeconds(1)
//                                .strafeRight(10)
//                                .build()
//                );
//        RoadRunnerBotEntity BlueLeftCycle3 = new DefaultBotBuilder(meepMeep)
//                // Set bot constraints: maxVel, maxAccel, maxAngVel, maxAngAccel, track width
//                .setColorScheme(new ColorSchemeBlueLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(35, 61.5, Math.toRadians(270)))
//                                .splineToConstantHeading(new Vector2d(24,12), Math.toRadians(180))
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .splineToConstantHeading(new Vector2d(50,12), Math.toRadians(0))
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(12)
//                                .waitSeconds(1)
//                                .strafeLeft(35)
//                                .waitSeconds(1)
//                                .build()
//                );
//        RoadRunnerBotEntity BlueRightCycle2 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeBlueLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(-35, 61.5, Math.toRadians(270)))
//                                .splineToConstantHeading(new Vector2d(-24,12), Math.toRadians(0))
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .build()
//                );
//        RoadRunnerBotEntity BlueRightCycle3 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeBlueLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(-35, 61.5, Math.toRadians(270)))
//                                .splineToConstantHeading(new Vector2d(-24,12), Math.toRadians(0))
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(35)
//                                .waitSeconds(1)
//                                .build()
//                );
//        RoadRunnerBotEntity BlueRightCycle1 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeBlueLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(-35, 61.5, Math.toRadians(270)))
//                                .splineToConstantHeading(new Vector2d(-24,12), Math.toRadians(0))
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(15)
//                                .waitSeconds(1)
//                                .build()
//                );
//        RoadRunnerBotEntity RedLeftCycle2 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeRedLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(-35, -61.5, Math.toRadians(90)))
//                                .splineToConstantHeading(new Vector2d(-24,-12), Math.toRadians(720))
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(13)
//                                .build()
//                );
//        RoadRunnerBotEntity RedLeftCycle1 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeRedLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(-35, -61.5, Math.toRadians(90)))
//                                .splineToConstantHeading(new Vector2d(-24,-12), Math.toRadians(720))
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .build()
//                );
//        RoadRunnerBotEntity RedLeftCycle3 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeRedLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(-35, -61.5, Math.toRadians(90)))
//                                .splineToConstantHeading(new Vector2d(-24,-12), Math.toRadians(720))
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(10)
//                                .turn(Math.toRadians(90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(-90))
//                                .strafeRight(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(32)
//                                .build()
//                );
//
//        RoadRunnerBotEntity RedRightCycle2 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeRedLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(35, -61.5, Math.toRadians(90)))
//                                .splineToConstantHeading(new Vector2d(24,-12), Math.toRadians(910))
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(12)
//                                .waitSeconds(1)
//                                .build()
//                );
//        RoadRunnerBotEntity RedRightCycle1 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeRedLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(35, -61.5, Math.toRadians(90)))
//                                .splineToConstantHeading(new Vector2d(24,-12), Math.toRadians(910))
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeLeft(12)
//                                .waitSeconds(1)
//                                .build()
//                );
//        RoadRunnerBotEntity RedRightCycle3 = new DefaultBotBuilder(meepMeep)
//                .setColorScheme(new ColorSchemeRedLight())
//                .setConstraints(60, 60, Math.toRadians(180), Math.toRadians(180), 15)
//                .setDimensions(13.5, 17)
//                .followTrajectorySequence(drive ->
//                        drive.trajectorySequenceBuilder(new Pose2d(35, -61.5, Math.toRadians(90)))
//                                .splineToConstantHeading(new Vector2d(24,-12), Math.toRadians(910))
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(10)
//                                .turn(Math.toRadians(-90))
//                                .forward(15)
//                                .waitSeconds(.5)
//                                .back(15)
//                                .turn(Math.toRadians(90))
//                                .strafeLeft(10)
//                                .waitSeconds(.5)
//                                .strafeRight(35)
//                                .waitSeconds(1)
//                                .build()
//                );